// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 68wGqrWvUbUk9uG76N3xHk
// Component: t5yBiOJTZxA
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Checkbox from "../../Checkbox"; // plasmic-import: NK-xeF1iGEb/component
import InputNumber from "../../InputNumber"; // plasmic-import: VngmHdU9aX0/component
import TextInput from "../../TextInput"; // plasmic-import: UzcYFC-NJii/component
import Button from "../../Button"; // plasmic-import: UCG438gq_ly/component
import Timeline from "../../Timeline"; // plasmic-import: 0RHyvgnmPT/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_acc_tez_wizard.module.css"; // plasmic-import: 68wGqrWvUbUk9uG76N3xHk/projectcss
import sty from "./PlasmicChoosePasses.module.css"; // plasmic-import: t5yBiOJTZxA/css

import SearchsvgIcon from "./icons/PlasmicIcon__Searchsvg"; // plasmic-import: M1v116-IU5V/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: gYo0rjvqId9/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: XoAtNs3eY9L/icon
import WizardSvgrepoComsvg2Icon from "./icons/PlasmicIcon__WizardSvgrepoComsvg2"; // plasmic-import: ppcK-LiUA7/icon
import screenShot20220619At70250PMpngCyEWdgYSm from "./images/screenShot20220619At70250PMpng.png"; // plasmic-import: cyEWdgYSm/picture

export type PlasmicChoosePasses__VariantMembers = {};

export type PlasmicChoosePasses__VariantsArgs = {};
type VariantPropType = keyof PlasmicChoosePasses__VariantsArgs;
export const PlasmicChoosePasses__VariantProps = new Array<VariantPropType>();

export type PlasmicChoosePasses__ArgsType = {};
type ArgPropType = keyof PlasmicChoosePasses__ArgsType;
export const PlasmicChoosePasses__ArgProps = new Array<ArgPropType>();

export type PlasmicChoosePasses__OverridesType = {
  root?: p.Flex<"div">;
  columns?: p.Flex<"div">;
  h1?: p.Flex<"h1">;
  dayPassCheckbox?: p.Flex<typeof Checkbox>;
  dayPassTezos?: p.Flex<typeof InputNumber>;
  dayPassPrice?: p.Flex<typeof InputNumber>;
  weeklyPassCheckbox?: p.Flex<typeof Checkbox>;
  weeklyPassTezos?: p.Flex<typeof InputNumber>;
  weeklyPassPrice?: p.Flex<typeof InputNumber>;
  yearlyPassCheckbox?: p.Flex<typeof Checkbox>;
  yearlyPassTezos?: p.Flex<typeof InputNumber>;
  yearlyPassPrice?: p.Flex<typeof InputNumber>;
  specialPassCheckbox?: p.Flex<typeof Checkbox>;
  specialPassTezos?: p.Flex<typeof InputNumber>;
  specialPassPrice?: p.Flex<typeof InputNumber>;
  backButton?: p.Flex<typeof Button>;
  nextButton?: p.Flex<typeof Button>;
  svg?: p.Flex<"svg">;
  img?: p.Flex<typeof p.PlasmicImg>;
  timeline?: p.Flex<typeof Timeline>;
};

export interface DefaultChoosePassesProps {
  className?: string;
}

export const defaultChoosePasses__Args: Partial<PlasmicChoosePasses__ArgsType> =
  {};

function PlasmicChoosePasses__RenderFunc(props: {
  variants: PlasmicChoosePasses__VariantsArgs;
  args: PlasmicChoosePasses__ArgsType;
  overrides: PlasmicChoosePasses__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultChoosePasses__Args, props.args);
  const $props = args;
  const $ctx = ph.useDataEnv?.() || {};

  return (
    <React.Fragment>
      {}
      {}

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          {true ? (
            <div className={classNames(projectcss.all, sty.freeBox__fJp20)} />
          ) : null}

          <div
            data-plasmic-name={"columns"}
            data-plasmic-override={overrides.columns}
            className={classNames(projectcss.all, sty.columns)}
          >
            <div className={classNames(projectcss.all, sty.column__eEAqS)}>
              <div className={classNames(projectcss.all, sty.freeBox__fdw4K)}>
                <div className={classNames(projectcss.all, sty.freeBox__nK4Bp)}>
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {"Choose Your Passes"}
                  </h1>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dXhnB
                    )}
                  >
                    {"Select the types of passes you would like to use."}
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox___14SYr)}
                  >
                    <Checkbox
                      data-plasmic-name={"dayPassCheckbox"}
                      data-plasmic-override={overrides.dayPassCheckbox}
                      className={classNames(
                        "__wab_instance",
                        sty.dayPassCheckbox
                      )}
                      name={"" as const}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zbwQs
                        )}
                      >
                        {"Day Pass"}
                      </div>
                    </Checkbox>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uUYw
                      )}
                    >
                      {
                        "Day Pass Allows User Access for 24 hours from time of purchase."
                      }
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___5Ldzc
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__lIYzR
                        )}
                      >
                        {"Price:"}
                      </div>

                      <InputNumber
                        data-plasmic-name={"dayPassTezos"}
                        data-plasmic-override={overrides.dayPassTezos}
                        className={classNames(
                          "__wab_instance",
                          sty.dayPassTezos
                        )}
                        placeholder={"0" as const}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__q7U8I
                        )}
                      >
                        {"Tezos"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zzjlJ
                        )}
                      >
                        {"or"}
                      </div>

                      <InputNumber
                        data-plasmic-name={"dayPassPrice"}
                        data-plasmic-override={overrides.dayPassPrice}
                        className={classNames(
                          "__wab_instance",
                          sty.dayPassPrice
                        )}
                        placeholder={"0" as const}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__guq11
                        )}
                      >
                        {"Dollars"}
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__irkOz)}
                  >
                    <Checkbox
                      data-plasmic-name={"weeklyPassCheckbox"}
                      data-plasmic-override={overrides.weeklyPassCheckbox}
                      className={classNames(
                        "__wab_instance",
                        sty.weeklyPassCheckbox
                      )}
                      name={"" as const}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__yalWa
                        )}
                      >
                        {"Weekly Pass"}
                      </div>
                    </Checkbox>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jEsm1
                      )}
                    >
                      {
                        "Weekly  Pass Allows User Access for 7 Days from time of purchase."
                      }
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__p4MLy)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___8Iau
                        )}
                      >
                        {"Price:"}
                      </div>

                      <InputNumber
                        data-plasmic-name={"weeklyPassTezos"}
                        data-plasmic-override={overrides.weeklyPassTezos}
                        className={classNames(
                          "__wab_instance",
                          sty.weeklyPassTezos
                        )}
                        placeholder={"0" as const}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pvf5A
                        )}
                      >
                        {"Tezos"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__rnmlB
                        )}
                      >
                        {"or"}
                      </div>

                      <InputNumber
                        data-plasmic-name={"weeklyPassPrice"}
                        data-plasmic-override={overrides.weeklyPassPrice}
                        className={classNames(
                          "__wab_instance",
                          sty.weeklyPassPrice
                        )}
                        placeholder={"0" as const}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___0ZSnM
                        )}
                      >
                        {"Dollars"}
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__p26XT)}
                  >
                    <Checkbox
                      data-plasmic-name={"yearlyPassCheckbox"}
                      data-plasmic-override={overrides.yearlyPassCheckbox}
                      className={classNames(
                        "__wab_instance",
                        sty.yearlyPassCheckbox
                      )}
                      name={"" as const}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__j39Hb
                        )}
                      >
                        {"Yearly Pass"}
                      </div>
                    </Checkbox>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__oew3
                      )}
                    >
                      {
                        "Yearly Pass Allows User Access for 365 Days from time of purchase."
                      }
                    </div>

                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___455MR
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__udDdb
                        )}
                      >
                        {"Price:"}
                      </div>

                      <InputNumber
                        data-plasmic-name={"yearlyPassTezos"}
                        data-plasmic-override={overrides.yearlyPassTezos}
                        className={classNames(
                          "__wab_instance",
                          sty.yearlyPassTezos
                        )}
                        placeholder={"0" as const}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wnhvk
                        )}
                      >
                        {"Tezos"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pit0J
                        )}
                      >
                        {"or"}
                      </div>

                      <InputNumber
                        data-plasmic-name={"yearlyPassPrice"}
                        data-plasmic-override={overrides.yearlyPassPrice}
                        className={classNames(
                          "__wab_instance",
                          sty.yearlyPassPrice
                        )}
                        placeholder={"0" as const}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___7Uzaz
                        )}
                      >
                        {"Dollars"}
                      </div>
                    </div>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__rNxAk)}
                  >
                    <Checkbox
                      data-plasmic-name={"specialPassCheckbox"}
                      data-plasmic-override={overrides.specialPassCheckbox}
                      className={classNames(
                        "__wab_instance",
                        sty.specialPassCheckbox
                      )}
                      name={"" as const}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__taBuF
                        )}
                      >
                        {"Special Event Pass"}
                      </div>
                    </Checkbox>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bfQy0
                      )}
                    >
                      {
                        "Special Event Pass Allows User Access to a single event."
                      }
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__cR6W)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__uh3Qf
                        )}
                      >
                        {"Price:"}
                      </div>

                      <InputNumber
                        data-plasmic-name={"specialPassTezos"}
                        data-plasmic-override={overrides.specialPassTezos}
                        className={classNames(
                          "__wab_instance",
                          sty.specialPassTezos
                        )}
                        placeholder={"0" as const}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__s0Kz4
                        )}
                      >
                        {"Tezos"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__myyks
                        )}
                      >
                        {"or"}
                      </div>

                      <InputNumber
                        data-plasmic-name={"specialPassPrice"}
                        data-plasmic-override={overrides.specialPassPrice}
                        className={classNames(
                          "__wab_instance",
                          sty.specialPassPrice
                        )}
                        placeholder={"0" as const}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__rJfx0
                        )}
                      >
                        {"Dollars"}
                      </div>
                    </div>
                  </div>

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__gfUiO)}
                    >
                      <Checkbox
                        className={classNames(
                          "__wab_instance",
                          sty.checkbox__ypLy
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__elT4R
                          )}
                        >
                          {"Weekly  Pass"}
                        </div>
                      </Checkbox>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__bOWot
                        )}
                      >
                        {"Price:"}
                      </div>

                      <TextInput
                        className={classNames(
                          "__wab_instance",
                          sty.textInput__i9JYj
                        )}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__hvDy
                        )}
                      >
                        {"Tezos"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__sfZrs
                        )}
                      >
                        {"or"}
                      </div>

                      <TextInput
                        className={classNames(
                          "__wab_instance",
                          sty.textInput__k6VqD
                        )}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ukg2K
                        )}
                      >
                        {"Dollars"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___0VX
                        )}
                      >
                        {
                          "Weekly  Pass Allows User Access for 7 Days from time of purchase."
                        }
                      </div>
                    </div>
                  ) : null}
                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__gbSc)}
                    >
                      <Checkbox
                        className={classNames(
                          "__wab_instance",
                          sty.checkbox__ewUk
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ljT0L
                          )}
                        >
                          {"Yearly Pass"}
                        </div>
                      </Checkbox>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__rPh7Q
                        )}
                      >
                        {"Price:"}
                      </div>

                      <TextInput
                        className={classNames(
                          "__wab_instance",
                          sty.textInput__yaGdR
                        )}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__pe1Xl
                        )}
                      >
                        {"Tezos"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___0JpD
                        )}
                      >
                        {"or"}
                      </div>

                      <TextInput
                        className={classNames(
                          "__wab_instance",
                          sty.textInput___25YhH
                        )}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__y8CaY
                        )}
                      >
                        {"Dollars"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__lic6Z
                        )}
                      >
                        {
                          "Weekly  Pass Allows User Access for 365 Days from time of purchase."
                        }
                      </div>
                    </div>
                  ) : null}
                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__mZxa)}
                    >
                      <Checkbox
                        className={classNames(
                          "__wab_instance",
                          sty.checkbox__r8Gwr
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___4HmTn
                          )}
                        >
                          {"Special Event Pass"}
                        </div>
                      </Checkbox>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___1FnOq
                        )}
                      >
                        {"Price:"}
                      </div>

                      <TextInput
                        className={classNames(
                          "__wab_instance",
                          sty.textInput__dmvNl
                        )}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tPf1Y
                        )}
                      >
                        {"Tezos"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__a99W
                        )}
                      >
                        {"or"}
                      </div>

                      <TextInput
                        className={classNames(
                          "__wab_instance",
                          sty.textInput__mSayv
                        )}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__nBeXi
                        )}
                      >
                        {"Dollars"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ia94W
                        )}
                      >
                        {
                          "Special Event Pass Allows User Access to a single event."
                        }
                      </div>
                    </div>
                  ) : null}
                </div>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__xGnNx)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__pgxTa)}
                  />

                  <Button
                    data-plasmic-name={"backButton"}
                    data-plasmic-override={overrides.backButton}
                    className={classNames("__wab_instance", sty.backButton)}
                  >
                    {"Back"}
                  </Button>

                  <Button
                    data-plasmic-name={"nextButton"}
                    data-plasmic-override={overrides.nextButton}
                    className={classNames("__wab_instance", sty.nextButton)}
                  >
                    {"Next"}
                  </Button>
                </p.Stack>
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.column__uUAkl)}>
              {true ? (
                <div className={classNames(projectcss.all, sty.freeBox__fBvVl)}>
                  <WizardSvgrepoComsvg2Icon
                    data-plasmic-name={"svg"}
                    data-plasmic-override={overrides.svg}
                    className={classNames(projectcss.all, sty.svg)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ceZ4H
                    )}
                  >
                    {"AccTez Wizard"}
                  </div>

                  <p.PlasmicImg
                    data-plasmic-name={"img"}
                    data-plasmic-override={overrides.img}
                    alt={""}
                    className={classNames(sty.img)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    loading={"lazy" as const}
                    src={{
                      src: screenShot20220619At70250PMpngCyEWdgYSm,
                      fullWidth: 627,
                      fullHeight: 419,
                      aspectRatio: undefined
                    }}
                  />
                </div>
              ) : null}

              <Timeline
                data-plasmic-name={"timeline"}
                data-plasmic-override={overrides.timeline}
                className={classNames("__wab_instance", sty.timeline)}
              />
            </div>
          </div>
        </p.Stack>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "columns",
    "h1",
    "dayPassCheckbox",
    "dayPassTezos",
    "dayPassPrice",
    "weeklyPassCheckbox",
    "weeklyPassTezos",
    "weeklyPassPrice",
    "yearlyPassCheckbox",
    "yearlyPassTezos",
    "yearlyPassPrice",
    "specialPassCheckbox",
    "specialPassTezos",
    "specialPassPrice",
    "backButton",
    "nextButton",
    "svg",
    "img",
    "timeline"
  ],
  columns: [
    "columns",
    "h1",
    "dayPassCheckbox",
    "dayPassTezos",
    "dayPassPrice",
    "weeklyPassCheckbox",
    "weeklyPassTezos",
    "weeklyPassPrice",
    "yearlyPassCheckbox",
    "yearlyPassTezos",
    "yearlyPassPrice",
    "specialPassCheckbox",
    "specialPassTezos",
    "specialPassPrice",
    "backButton",
    "nextButton",
    "svg",
    "img",
    "timeline"
  ],
  h1: ["h1"],
  dayPassCheckbox: ["dayPassCheckbox"],
  dayPassTezos: ["dayPassTezos"],
  dayPassPrice: ["dayPassPrice"],
  weeklyPassCheckbox: ["weeklyPassCheckbox"],
  weeklyPassTezos: ["weeklyPassTezos"],
  weeklyPassPrice: ["weeklyPassPrice"],
  yearlyPassCheckbox: ["yearlyPassCheckbox"],
  yearlyPassTezos: ["yearlyPassTezos"],
  yearlyPassPrice: ["yearlyPassPrice"],
  specialPassCheckbox: ["specialPassCheckbox"],
  specialPassTezos: ["specialPassTezos"],
  specialPassPrice: ["specialPassPrice"],
  backButton: ["backButton"],
  nextButton: ["nextButton"],
  svg: ["svg"],
  img: ["img"],
  timeline: ["timeline"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  columns: "div";
  h1: "h1";
  dayPassCheckbox: typeof Checkbox;
  dayPassTezos: typeof InputNumber;
  dayPassPrice: typeof InputNumber;
  weeklyPassCheckbox: typeof Checkbox;
  weeklyPassTezos: typeof InputNumber;
  weeklyPassPrice: typeof InputNumber;
  yearlyPassCheckbox: typeof Checkbox;
  yearlyPassTezos: typeof InputNumber;
  yearlyPassPrice: typeof InputNumber;
  specialPassCheckbox: typeof Checkbox;
  specialPassTezos: typeof InputNumber;
  specialPassPrice: typeof InputNumber;
  backButton: typeof Button;
  nextButton: typeof Button;
  svg: "svg";
  img: typeof p.PlasmicImg;
  timeline: typeof Timeline;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicChoosePasses__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicChoosePasses__VariantsArgs;
    args?: PlasmicChoosePasses__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicChoosePasses__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicChoosePasses__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicChoosePasses__ArgProps,
      internalVariantPropNames: PlasmicChoosePasses__VariantProps
    });

    return PlasmicChoosePasses__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicChoosePasses";
  } else {
    func.displayName = `PlasmicChoosePasses.${nodeName}`;
  }
  return func;
}

export const PlasmicChoosePasses = Object.assign(
  // Top-level PlasmicChoosePasses renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    columns: makeNodeComponent("columns"),
    h1: makeNodeComponent("h1"),
    dayPassCheckbox: makeNodeComponent("dayPassCheckbox"),
    dayPassTezos: makeNodeComponent("dayPassTezos"),
    dayPassPrice: makeNodeComponent("dayPassPrice"),
    weeklyPassCheckbox: makeNodeComponent("weeklyPassCheckbox"),
    weeklyPassTezos: makeNodeComponent("weeklyPassTezos"),
    weeklyPassPrice: makeNodeComponent("weeklyPassPrice"),
    yearlyPassCheckbox: makeNodeComponent("yearlyPassCheckbox"),
    yearlyPassTezos: makeNodeComponent("yearlyPassTezos"),
    yearlyPassPrice: makeNodeComponent("yearlyPassPrice"),
    specialPassCheckbox: makeNodeComponent("specialPassCheckbox"),
    specialPassTezos: makeNodeComponent("specialPassTezos"),
    specialPassPrice: makeNodeComponent("specialPassPrice"),
    backButton: makeNodeComponent("backButton"),
    nextButton: makeNodeComponent("nextButton"),
    svg: makeNodeComponent("svg"),
    img: makeNodeComponent("img"),
    timeline: makeNodeComponent("timeline"),

    // Metadata about props expected for PlasmicChoosePasses
    internalVariantProps: PlasmicChoosePasses__VariantProps,
    internalArgProps: PlasmicChoosePasses__ArgProps
  }
);

export default PlasmicChoosePasses;
/* prettier-ignore-end */
