// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 68wGqrWvUbUk9uG76N3xHk
// Component: JUWhA5Wcld
import * as React from "react";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import TextInput from "../../TextInput"; // plasmic-import: UzcYFC-NJii/component
import "@plasmicapp/react-web/lib/plasmic.css";
import sty from "./PlasmicTitleText.module.css"; // plasmic-import: JUWhA5Wcld/css

export const PlasmicTitleText__VariantProps = new Array();

export const PlasmicTitleText__ArgProps = new Array();

export const defaultTitleText__Args = {};

function PlasmicTitleText__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultTitleText__Args, props.args);
  const $props = args;
  const $ctx = ph.useDataEnv?.() || {};
  return (
    <TextInput
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.root)}
    />
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTitleText__ArgProps,
      internalVariantPropNames: PlasmicTitleText__VariantProps
    });

    return PlasmicTitleText__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTitleText";
  } else {
    func.displayName = `PlasmicTitleText.${nodeName}`;
  }
  return func;
}

export const PlasmicTitleText = Object.assign(
  // Top-level PlasmicTitleText renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicTitleText
    internalVariantProps: PlasmicTitleText__VariantProps,
    internalArgProps: PlasmicTitleText__ArgProps
  }
);

export default PlasmicTitleText;
/* prettier-ignore-end */
