// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 68wGqrWvUbUk9uG76N3xHk
// Component: JUWhA5Wcld
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import TextInput from "../../TextInput"; // plasmic-import: UzcYFC-NJii/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_acc_tez_wizard.module.css"; // plasmic-import: 68wGqrWvUbUk9uG76N3xHk/projectcss
import sty from "./PlasmicTitleText.module.css"; // plasmic-import: JUWhA5Wcld/css

import SearchsvgIcon from "./icons/PlasmicIcon__Searchsvg"; // plasmic-import: M1v116-IU5V/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: gYo0rjvqId9/icon

export type PlasmicTitleText__VariantMembers = {};

export type PlasmicTitleText__VariantsArgs = {};
type VariantPropType = keyof PlasmicTitleText__VariantsArgs;
export const PlasmicTitleText__VariantProps = new Array<VariantPropType>();

export type PlasmicTitleText__ArgsType = {};
type ArgPropType = keyof PlasmicTitleText__ArgsType;
export const PlasmicTitleText__ArgProps = new Array<ArgPropType>();

export type PlasmicTitleText__OverridesType = {
  root?: p.Flex<typeof TextInput>;
};

export interface DefaultTitleTextProps {
  className?: string;
}

export const defaultTitleText__Args: Partial<PlasmicTitleText__ArgsType> = {};

function PlasmicTitleText__RenderFunc(props: {
  variants: PlasmicTitleText__VariantsArgs;
  args: PlasmicTitleText__ArgsType;
  overrides: PlasmicTitleText__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultTitleText__Args, props.args);
  const $props = args;
  const $ctx = ph.useDataEnv?.() || {};

  return (
    <TextInput
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.root)}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: typeof TextInput;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTitleText__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTitleText__VariantsArgs;
    args?: PlasmicTitleText__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTitleText__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicTitleText__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTitleText__ArgProps,
      internalVariantPropNames: PlasmicTitleText__VariantProps
    });

    return PlasmicTitleText__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTitleText";
  } else {
    func.displayName = `PlasmicTitleText.${nodeName}`;
  }
  return func;
}

export const PlasmicTitleText = Object.assign(
  // Top-level PlasmicTitleText renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicTitleText
    internalVariantProps: PlasmicTitleText__VariantProps,
    internalArgProps: PlasmicTitleText__ArgProps
  }
);

export default PlasmicTitleText;
/* prettier-ignore-end */
